package cli

import (
	"fmt"
	"io"
	"unicode/utf8"
)

// safeTokenWriter streams generated byte tokens without allowing terminal
// control sequences. Newline and tab remain readable; other controls and
// invalid UTF-8 bytes are rendered as hexadecimal escapes.
type safeTokenWriter struct {
	writer  io.Writer
	pending []byte
}

func (renderer *safeTokenWriter) Write(data []byte) error {
	renderer.pending = append(renderer.pending, data...)
	for len(renderer.pending) > 0 {
		first := renderer.pending[0]
		if first < utf8.RuneSelf {
			renderer.pending = renderer.pending[1:]
			if first == '\n' || first == '\t' || first >= 0x20 && first != 0x7f {
				if _, err := renderer.writer.Write([]byte{first}); err != nil {
					return err
				}
			} else if _, err := fmt.Fprintf(renderer.writer, "\\x%02x", first); err != nil {
				return err
			}
			continue
		}
		if !utf8.FullRune(renderer.pending) {
			return nil
		}
		runeValue, size := utf8.DecodeRune(renderer.pending)
		if runeValue == utf8.RuneError && size == 1 {
			if _, err := fmt.Fprintf(renderer.writer, "\\x%02x", first); err != nil {
				return err
			}
			renderer.pending = renderer.pending[1:]
			continue
		}
		if _, err := renderer.writer.Write(renderer.pending[:size]); err != nil {
			return err
		}
		renderer.pending = renderer.pending[size:]
	}
	return nil
}

func (renderer *safeTokenWriter) Flush() error {
	for _, value := range renderer.pending {
		if _, err := fmt.Fprintf(renderer.writer, "\\x%02x", value); err != nil {
			return err
		}
	}
	renderer.pending = nil
	return nil
}
