// Copyright (c) 2026 OpenWALDO Project contributors
// Copyright (c) 2026 CtrlIQ, Inc.
// Copyright (c) 2026 Gregory M. Kurtzer
// SPDX-License-Identifier: Apache-2.0

package cli

import (
	"context"
	"io"
)

type Context struct {
	Execution context.Context
	JSON      bool
}

type Handler func(Context, []string, io.Writer, io.Writer) error

// Command describes one stable part of the WALDO command vocabulary. Phase 0
// intentionally contains no operational handlers: the command tree is a UX
// contract that implementation slices will fill in one domain at a time.
type Command struct {
	Name     string
	Summary  string
	Usage    string
	Details  string
	Children []Command
	Handler  Handler
}

func commandTree() Command {
	return Command{
		Name:    "waldo",
		Summary: "Build and use auditable AI training data",
		Details: "Global options:\n  --json     Emit structured command output; progress remains on stderr.\n  --help     Show command help.\n  --version  Show the WALDO version.\n\nExplicit index paths discover their checkout. Logical or omitted index paths use the current checkout, then the checkout set by `waldo config set index <path>`.",
		Children: []Command{
			{Name: "index", Summary: "Manage indexed training data", Details: "Index paths are positional. Existing checkout, subtree, corpus-directory, and manifest paths discover their enclosing checkout automatically. With no path, WALDO discovers from the current directory. Recursive commands begin at the selected path.", Children: []Command{
				{Name: "init", Summary: "Initialize an empty index", Usage: "waldo index init <directory> [--json]", Details: "Creates the smallest valid schema-1 index.yaml in a new or empty directory. Readers accept existing JSON or YAML metadata, while all new WALDO index writes use YAML. The command refuses nonempty directories and does not initialize Git, configure a lookaside, or create a corpus.", Handler: runIndexInit},
				{Name: "list", Summary: "List all corpora beneath an index path", Usage: "waldo index list [path] [--json]", Handler: runIndexList},
				{Name: "show", Summary: "Show an index entry or corpus manifest", Usage: "waldo index show [path] [--json]", Handler: runIndexShow},
				{Name: "summary", Summary: "Summarize corpora, licenses, and totals", Usage: "waldo index summary [path] [--json]", Handler: runIndexSummary},
				{Name: "verify", Summary: "Verify an index and its canonical object locations", Usage: "waldo index verify [path] [--offline|--objects] [--json]", Details: "Verification levels:\n  (default)  Recursively validate metadata, then check every canonical object URL and declared size without downloading bodies.\n  --objects  Download every referenced object, verify its SHA-256, then purge it after success.\n  --offline  Validate only local index and manifest structure; make no network requests.\n\n  path       Existing checkout, index directory, corpus directory, or manifest. WALDO discovers the checkout from this path and recurses beneath it. When omitted, discovery starts at the current directory.\n\nMirrors never hide an unavailable canonical URL during the default check.", Handler: runIndexVerify},
				{Name: "audit", Summary: "Download and validate every indexed record", Usage: "waldo index audit [path] [--workers <n>] [--json]", Details: "Discovers the checkout from the positional path, recurses beneath that selection, downloads each unique shard through the configured lookaside, runs the same full validator as `waldo shard audit`, detects duplicate record IDs across shards, and compares audited totals with the index manifests. Shards are validated concurrently with a conservative automatic worker count; --workers sets 1..32 explicitly.", Handler: runIndexAudit},
				{Name: "ingest", Summary: "Ingest acquired material into an index", Usage: "waldo index ingest <input-or-recipe> <destination> [metadata options] [--dry-run] [--json]", Details: "Arguments:\n  <input-or-recipe>  A file, recursively scanned directory, or strict waldo-ingest-recipe YAML/JSON file.\n  <destination>       New corpus path. An absolute or ./ path discovers its checkout; a logical path uses the checkout containing the current directory.\n\nRequired: direct input only\n  --title             Human-readable corpus title.\n  --license           License applying to this contribution.\n  --source            Acquisition/source URL recorded in provenance.\n  --source-category   GPAI-compatible source category.\n\nDirect input options:\n  --description       Corpus description; WALDO generates a default otherwise.\n  --source-name       Source label; defaults from the destination name.\n  --text-column       Raw-Parquet text column when it cannot be inferred.\n  --input-profile     Strict standalone YAML/JSON declarative input profile.\n\nUniversal option:\n  --dry-run           Direct input is probed; recipe input resolves and hashes commands but never executes them.\n\nAn ingest recipe owns all corpus metadata and rejects metadata flags. Each step uses `exec`: a bare command resolves through PATH, while a value containing a path separator is explicit and relative to the recipe file unless absolute. Commands run directly and sequentially with one WALDO-owned temporary directory as their working directory and WALDO_FETCH_DIR; no shell is implied. WALDO then uses the normal probe, conversion, publication, purge, and contribution path. Set machine locations with `waldo config set`; ingestion has no transport or scratch flags.", Handler: runIndexIngest},
				{Name: "update", Summary: "Append or completely rebuild an existing corpus", Usage: "waldo index update <input-or-recipe> <manifest> [--rebuild-shards] [metadata options] [--dry-run] [--json]", Details: "The target must resolve exactly one existing manifest. Normal update audits existing shards, seeds exact content identities into a disk-backed set, and publishes only new records. --rebuild-shards treats the supplied input or ingest recipe as the complete authoritative corpus, does not download old shards, and replaces the shard and source set. Both modes pin the original manifest, use the normal streaming publication journal, and write touched metadata as schema-1 YAML while listing superseded JSON/YML files for removal. Ingest recipes receive WALDO_UPDATE_STATE with existing source and aggregate facts.", Handler: runIndexUpdate},
				{Name: "export", Summary: "Export a verified corpus selection and BOM", Usage: "waldo index export <path...> <directory> [--format native|jsonl] [--license <glob,...>] [--exclude-license <glob,...>] [--force] [--json]", Details: "Arguments:\n  <path...>           One or more corpus or index paths. The first discovers the checkout; later logical paths use that same checkout.\n  <directory>         Required local destination; always the final positional argument.\n\nOptions:\n  --format native     Preserve canonical Parquet objects (default).\n  --format jsonl      Stream verified Parquet records into JSONL.\n  --license           Include matching license identifiers.\n  --exclude-license   Exclude matching license identifiers.\n  --force             Replace conflicting export files; matching files resume safely.\n\nThe export contains data files and EXPORT.json with its OpenWALDO BOM. Downloaded scratch objects are purged only after both are complete.", Handler: runIndexExport},
				{Name: "remove", Summary: "Remove a corpus from the current index revision"},
			}},
			{Name: "shard", Summary: "Inspect and audit local canonical Parquet shards", Details: "Shard commands operate directly on local Parquet files. Summary and audit accept files, shell-expanded paths, glob patterns, and recursively scanned directories.", Children: []Command{
				{Name: "summary", Summary: "Aggregate shard footer and record totals", Usage: "waldo shard summary <path...> [--json]", Handler: runShardSummary},
				{Name: "audit", Summary: "Validate every record in one or more shards", Usage: "waldo shard audit <path...> [--workers <n>] [--json]", Details: "Streams every selected record, recomputes content hashes and reference token counts, validates required fields and metadata, and detects duplicate record IDs across the complete selection. Shards are validated concurrently with a conservative automatic worker count; --workers sets 1..32 explicitly.", Handler: runShardAudit},
				{Name: "list-records", Summary: "List compact record summaries from one shard", Usage: "waldo shard list-records <shard-file> [--json]", Handler: runShardListRecords},
				{Name: "export-record", Summary: "Write one record's text to standard output", Usage: "waldo shard export-record <shard-file> <record-id>", Handler: runShardExportRecord},
			}},
			{Name: "lookaside", Summary: "Inspect and maintain content-addressed objects", Children: []Command{
				{Name: "login", Summary: "Verify and store S3 credentials in ~/.waldo", Usage: "waldo lookaside login [--json]", Details: "Requires a configured s3:// lookaside. Prompts interactively for an S3 access key and hidden secret key. WALDO writes, lists, inspects, reads, and deletes a tiny probe object beneath the configured prefix before storing bucket-scoped credentials in ~/.waldo/credentials with mode 0600. Credentials are never written to WALDO configuration, output, manifests, or command history.", Handler: runLookasideLogin},
				{Name: "logout", Summary: "Remove stored S3 credentials", Usage: "waldo lookaside logout [--json]", Handler: runLookasideLogout},
				{Name: "list", Summary: "List lookaside objects and optional index references", Usage: "waldo lookaside list [index-path] [--all] [--json]", Details: "For S3, inventories the configured lookaside's entire bucket without downloading object bodies. A file:// lookaside inventories its configured root. With an index path, only matching object hashes are shown; --all includes unmatched objects with `--` in the INDEX column. Human output is only a compact header and rows: a 16-character object prefix, size, immutable storage timestamp, storage prefix, and index reference. JSON retains complete hashes, paths, timestamps, references, inventory context, and totals. Unmatched objects are not necessarily safe to remove; another index or BOM may still reference them.", Handler: runLookasideList},
				{Name: "status", Summary: "Show retained cache, download scratch, and storage", Usage: "waldo lookaside status [--json]", Handler: runLookasideStatus},
				{Name: "verify", Summary: "Scrub leftover objects against their hashes", Usage: "waldo lookaside verify [--json]", Handler: runLookasideVerify},
				{Name: "mirror", Summary: "Copy verified objects to another lookaside"},
				{Name: "rm", Summary: "Remove explicitly named lookaside objects", Usage: "waldo lookaside rm <sha256>... [--json]", Details: "Every object name must be a complete 64-character lowercase SHA-256. WALDO preflights the entire list against the configured writable lookaside before deleting anything. URLs, prefixes, globs, and reachability-based garbage collection are intentionally unsupported.", Handler: runLookasideRemove},
			}},
			{Name: "model", Summary: "Create, train, compose, and use auditable models", Children: []Command{
				{Name: "init", Summary: "Initialize an untrained model", Usage: "waldo model init <name> --preset <preset> [--json]", Details: "Creates an immutable architecture under model.root without training it. Available presets: 10m, 35m, 90m, 300m, 1b, 3b, 7b, 13b, 34b, 70b.", Handler: runModelInit},
				{Name: "pull", Summary: "Pull training-quality open weights", Usage: "waldo model pull <name> <huggingface-source> [--json]", Details: "Pulls a Hugging Face Safetensors model, resolves its requested reference to an immutable repository revision, hashes every acquired artifact, validates the architecture/tokenizer/tensor contract, and losslessly normalizes compatible tensor names into a managed WALDO model with a separate origin BOM. The initial implementation supports standard Llama configuration using OpenWALDOByteTokenizer. HF_TOKEN and the standard Hugging Face token file are honored for gated repositories.", Handler: runModelPull},
				{Name: "list", Summary: "List locally managed models", Usage: "waldo model list [pattern...] [--json]", Details: "Patterns match model names and use shell-style *, ?, and character classes. With no patterns, every valid model beneath model.root is listed.", Handler: runModelList},
				{Name: "summary", Summary: "Summarize architecture and training history", Usage: "waldo model summary <name> [--json]", Handler: runModelSummary},
				{Name: "bom", Summary: "Emit a model OpenWALDO BOM", Usage: "waldo model bom <name> [output.json] [--json]", Details: "Writes canonical JSON to stdout when output is omitted. An existing output file is never replaced implicitly. Paths are portable and relative to the model root: either model.root/<name> or the root of a model export. A pulled model selects current_origin_sha256 until a complete real run supersedes it; runs retain backend and simulation identity without removing historical provenance.", Handler: runModelBOM},
				{Name: "forecast", Summary: "Estimate viable GPU configurations and runtime", Usage: "waldo model forecast <compose.yaml> | <index-path...> [--json]", Details: "A model compose uses its declared architecture and complete training budget. One or more index paths resolve a deduplicated selection, recommend the largest model rung supplied by roughly 20 tokens per parameter, and forecast one pass over the selected tokens. Explicit paths discover their checkout; logical paths use the current or configured index. Verified completed local runs calibrate only the exact accelerator and GPU count observed; unmatched rows retain the versioned catalog assumptions. Human output lists only configurations that fit, sorted from slowest to fastest. Approximate time is shown in hours below 100 hours, then in days. Forecast creates no model state.", Handler: runModelForecast},
				{Name: "train", Summary: "Train an existing model on indexed corpora", Usage: "waldo model train <name> <index-path...> [--epochs <n>] [--json]", Details: "Recursively resolves and deduplicates index selections, materializes hash-verified shards through the configured cache, audits every canonical record, and appends one explicit training run. --epochs controls complete passes and defaults to 1. A deterministic bounded 1% held-out set is excluded from every epoch and pinned in the run BOM for real loss/perplexity evaluation. WALDO counts the remaining exact model-token targets and derives optimizer steps. Atomic checkpoint bundles contain weights, optimizer state, runtime random state, step, and token position. Repeating the exact command after an interrupted run resumes that same run and records a new attempt; changed inputs or parameters create a new run. The automatic backend selects MLX on Apple Silicon; on Linux it prefers an installed TorchTitan, then PyTorch. An unavailable backend fails before creating a run and prints installation guidance. Simulation is never selected automatically.", Handler: runModelTrain},
				{Name: "compose", Summary: "Create and train from a model compose", Usage: "waldo model compose <name> <compose-file> [--replace] [--json]", Details: "A compose declares architecture and ordered training stages whose corpora are logical or explicit index paths. An optional base.model names a pulled local starting point; WALDO verifies its current origin, an optional origin_sha256 assertion, and exact architecture equality. WALDO preflights every stage before publishing the model. Existing names are refused unless --replace is present. Work is retained in a content-identified transaction after interruption; repeating the exact command resumes it, and the old model remains published until every replacement stage completes.", Handler: runModelCompose},
				{Name: "export", Summary: "Export a model release package", Usage: "waldo model export <name> <directory> [--format waldo|huggingface|mlx|gguf|ollama] [--quant 2|3|4|5|6|8] [--calibration <index-path>] [--allow-incomplete] [--json]", Details: "Each format is written atomically to a new directory and contains BOM.json plus EU-BOM.json. Runtime exports select and verify the current pulled origin or complete real run. Hugging Face and MLX preserve tensor bytes while mapping names to standard Llama. GGUF streams a precision-preserving GGUF v3 conversion by default; --quant selects a simple bit-level profile implemented by the installed upstream llama.cpp tools. --calibration is valid only with --quant: it resolves one WALDO index selection, retrieves and audits only enough deterministic verified shards for a bounded 100,000-byte-token importance sample, and embeds the evidence in BOM.json. Calibration measures quantization sensitivity; it does not train or change weights. Ollama adds a minimal Modelfile around the GGUF. disclosure.provider must point to a strict provider profile. Normal export fails closed when required disclosure facts are missing; --allow-incomplete emits a marked development draft. Configured signing is automatic and fail-closed; otherwise export succeeds with an unsigned warning.", Handler: runModelExport},
				{Name: "chat", Summary: "Generate with a trained local model", Usage: "waldo model chat <name> [prompt] [--max-tokens <n>] [--temperature <n>] [--top-p <n>] [--seed <n>] [--json]", Details: "With no prompt in a terminal, opens an interactive session with /clear, /help, and /exit. A positional prompt performs one-shot generation; when standard input is piped, its complete contents are the prompt. Human output streams safely to the terminal. --json is one-shot only and emits the completed result. WALDO selects the current pulled origin or real-weight run from the model BOM and verifies weights, configuration, and tokenizer hashes. Generation currently requires a compatible MLX runtime. Built-in pretrained models use raw causal continuation and may not behave like instruction-tuned assistants.", Handler: runModelChat},
				{Name: "rm", Summary: "Remove explicitly named local models", Usage: "waldo model rm <name...> [--json]", Details: "Names are preflighted as valid managed models before any removal. Paths, globs, and implicit reachability cleanup are unsupported.", Handler: runModelRemove},
			}},
			{Name: "bom", Summary: "Inspect and exchange provenance records", Children: []Command{
				{Name: "show", Summary: "Show an exported OpenWALDO BOM", Usage: "waldo bom show <export-directory|EXPORT.json> [--json]", Handler: runBOMShow},
				{Name: "verify", Summary: "Validate a BOM and hash its exported files", Usage: "waldo bom verify <export-directory|EXPORT.json> [--json]", Handler: runBOMVerify},
				{Name: "export", Summary: "Map a model BOM to a disclosure format", Usage: "waldo bom export <model-name-or-path> [output.json] --format eu-gpai [--provider <profile.json>] [--allow-incomplete] [--force] [--json]", Details: "Arguments:\n  <model-name-or-path>  Verified local model name or directory.\n  [output.json]        Optional destination. When omitted, the converted document is written to stdout.\n\nOptions:\n  --format eu-gpai     Pin and map the supported Commission template version.\n  --provider           Override disclosure.provider with a strict schema-1 provider profile.\n  --allow-incomplete   Emit a conspicuously marked draft when required facts are missing.\n  --force              Replace an existing output file; invalid when writing to stdout.\n\nNormal export fails before emitting anything if any required disclosure fact is absent. WALDO reports provenance gaps; it does not make a legal compliance finding or yet render the official editable document.", Handler: runBOMExport},
			}},
			{Name: "config", Summary: "Inspect and change machine-local preferences", Children: []Command{
				{Name: "show", Summary: "Show effective configuration", Usage: "waldo config show [--json]", Handler: runConfigShow},
				{Name: "get", Summary: "Discover configuration keys and values", Usage: "waldo config get [key-or-prefix] [--json]", Details: "With no argument, lists every supported configuration key. A prefix such as `lookaside` lists every matching key. An exact leaf such as `lookaside.region` prints only its value. Unset values remain visible.\n\nExamples:\n  waldo config get\n  waldo config get lookaside\n  waldo config get lookaside.region", Handler: runConfigGet},
				{Name: "set", Summary: "Set one configuration value", Usage: "waldo config set <key> <value...> [--json]", Details: "Keys:\n  index                 Default local WALDO index checkout.\n  lookaside             Writable s3:// or file:// lookaside URL.\n  lookaside.region      AWS region when it cannot be inferred.\n  lookaside.workers     Concurrent completed-shard uploads (1..32).\n  lookaside.mirrors     Ordered fallback read URLs; values replace the list.\n  lookaside.cache       Retained verified objects; default ~/.waldo/cache.\n  lookaside.cache.max-size  Retention bound; default 20GiB.\n  lookaside.scratch     Partial downloads; default beneath system temp.\n  ingest.staging        Ingestion recovery state; default beneath system temp.\n  model.root            Durable model artifacts; default ~/.waldo/models.\n  model.backend         auto (default), mlx, torchtitan, pytorch, or fake.\n  disclosure.provider  Strict provider-level disclosure JSON file.\n  signing.method       sigstore-keyless or sigstore-key.\n  signing.key          Private-key file used by sigstore-key.\n\nExamples:\n  waldo config set index /path/to/waldo-index\n  waldo config set lookaside file:///tmp/waldo-published\n  waldo config set lookaside s3://bucket/prefix\n  waldo config set lookaside.cache /fast-disk/waldo-cache\n  waldo config set lookaside.cache.max-size 100GiB\n  waldo config set disclosure.provider ./provider.json\n  waldo config set signing.method sigstore-keyless\n\nUse `waldo lookaside login` to store S3 keys in ~/.waldo/credentials. Environment and workload-role credentials remain available when no WALDO login exists.", Handler: runConfigSet},
				{Name: "unset", Summary: "Return one configuration value to its default", Usage: "waldo config unset <key> [--json]", Handler: runConfigUnset},
			}},
		},
	}
}
